kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "pipeline-terraform"
spec:
  source:
    git:
      uri: "https://github.com/maifujalam/openshift.git"
    contextDir: apps/terraform
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath:
