apiVersion: v1
kind: Service
metadata:
  name: v1-docker
  namespace: app1
spec:
  selector:
    app: v1
  ports:
  - nodePort: 0
    port: 80
    protocol: TCP
    targetPort: 5555
  type: ClusterIP
