pipeline {
    agent any
    triggers {
        pollSCM('*/5 * * * *')
    }
    stages {
        stage('Pull source code') {
            steps {
                echo "1.0"
                sh "ls -al"
//                 git 'https://github.com/maifujalam/openshift.git'
            }
        }
        stage('Build'){
            steps{

                echo "building"
            }
        }
    }
}
