pipeline {
    agent any
    triggers {
        pollSCM('*/30 * * * *')
    }
    stages {
        stage('Pull source code') {
            steps {
                echo "Pulling "
                git branch: 'master',url: 'https://github.com/maifujalam/openshift.git'
                echo "debug"
                sh "git branch"
                sh "ls -al"
            }
        }
        stage('Build'){
            steps{
                script{
                    openshift.withCluster(){
                        openshift.withProject(){
                            echo "Using project: ${openshift.project()}"
                            sh "ls -al"
                            openshiftBuild(buildConfig: 'docker-build',showBuildLogs: 'true')
                        }
                    }
                }
            }
        }
    }
}
