pipeline {
    agent any
    triggers {
        pollSCM('*/2 * * * *')
    }
    stages {
        stage('Pull source code') {
            steps {
                echo "Pulling "
//                 git 'https://github.com/maifujalam/openshift.git'
                    git branch
            }
        }
        stage('Build'){
            steps{
                echo "building"

            }
        }
    }
}
