apiVersion: v1
kind: Service
metadata:
  name: mongodb2
  namespace: app2
spec:
  selector:
    app: mongodb2
  ports:
  - nodePort: 0
    port: 80
    protocol: TCP
    targetPort: 27017
  type: NodePort
