apiVersion: v1
kind: Service
metadata:
  name: service-nodeport
  namespace: app1
spec:
  selector:
    app: mongodb
  ports:
  - nodePort: 30003
    port: 27017
    protocol: TCP
    targetPort: 27017
  type: NodePort
