apiVersion: v1
kind: Service
metadata:
  labels:
    app: v1
  name: v1
  namespace: app1
spec:
  clusterIP: 172.30.161.18
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 5555
  selector:
    deploymentconfig: v1
  type: ClusterIP
