kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "sample-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/maifujalam/openshift.git"
    contextDir: apps/flask-mongo2
  strategy:
    jenkinsPipelineStrategy:
#      jenkinsfilePath:
