apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: app3
  name: app3
  namespace: app3
spec:
  replicas: 1
  selector:
    deploymentconfig: app3
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: app3
        deploymentconfig: app3
    spec:
      containers:
        - image: docker.io/mongo:4.2-bionic
          imagePullPolicy: IfNotPresent
          name: app3
          ports:
            - containerPort: 27017
              protocol: TCP
  triggers:
    - type: ConfigChange
