---
# handlers file for k8sdeploy
- name: Start kubectl
  systemd:
    state: restarted
    daemon_reload: yes
    name: kubelet

- name: Restart docker 
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker

